spring.application.name: spring-data-service

server.port: 8081

#management.server.port: 8082

spring.data.cassandra:
  keyspace-name: ks_asset
  username: ks_asset
  password: ks_asset
  
  # Create the schema on the fly if it doesn't exist
  schema-action: CREATE_IF_NOT_EXISTS
  
  # Increase timeouts when connecting to Astra from a dev workstation
  request:
    timeout: 10s
  connection:
    connect-timeout: 10s
    init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: /Users/cedricklunven/Downloads/secure-connect-astrakathon-review.zip